version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: task-manager-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/task_manager
      JWT_SECRET: 'replace-with-a-long-random-secret'
      JWT_ACCESS_SECRET: 'dfsad1'
      JWT_REFRESH_SECRET: 'dfsad2'
      JWT_ACCESS_EXPIRES_IN: '15m'
      JWT_REFRESH_EXPIRES_IN: '7d'
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:5173
      RUN_SEEDERS_ON_START: 'true'
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: task-manager-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '5173:80'

volumes:
  mongo-data:
